### PR TITLE
Gh 72

### LINKED ISSUE #72: Game ui multi/solo
Just put the title on top (vertical/hor center?) and check that 1 to 5 opponnents are displaying ok

### PR DESCRIPTION
**Pull request by jeremie-gauthier**
I refactored the UI to include your changes.

**important:** To avoid any troubles, max players should now be 5 (owner + 4 opponents)

### CODE REVIEW

**Comment by nicolasvienot** [comment]
Just tried with 2 players, I have some strange placements. Both big and small screen.
Capture d’écran du 2020-11-11 20-54-32

**Comment by jeremie-gauthier** [comment]
@nicolasvienot check out the new board position

**Comment by nicolasvienot** [comment]
Looks a lot better! 
@jeremie-gauthier I just added some padding x on the opponent-grid to avoid this :
Capture d’écran du 2020-11-11 22-52-13

LGTM, you can merge it. Thanks!!!!!!!!!

**Review by nicolasvienot — APPROVED** [review]
Nice

**Pull request merged**
