### PR TITLE
Gh 14

### LINKED ISSUE #14: Async issue on Gravity Timer
I tried to enhance Tetris Game as marked in #13 

I have worked on the point that say the gravity timer should never stop on user action (e.g. rotation)

But I have found an issue that seems to be correlated with async state update.

Sometimes, when you want to make a rotation of the piece, it rotate well, but when the gravity action happens, it goes back to its original position (reverse rotate) one case down.

This happened with a gravity timer of 250ms.

What can possibly happens is that both actions plays concurrently with the same state of the piece and modify it the way they are programmed to.

I am not sure how to resolve this bug right now.

I wonder if working with a mutable ref of the piece could do it.

What do you think ?

### PR DESCRIPTION
**Pull request by jeremie-gauthier**
Closes #14

Here is a working version.

You can challenge it to track race conditions if there are !

### CODE REVIEW

**Comment by nicolasvienot** [comment]
All good I'll check that :+1:

**Comment by jeremie-gauthier** [comment]
In further research to optimize the stability of the game, here is what I found:

## Dependently update the tetris grid

I moved the management of the grid state out of the GameContext.
I created a useState hook to be able to update it regarding of the previous state.
[More information here](https://kentcdodds.com/blog/use-state-lazy-initialization-and-function-updates/)

Doing so:
```
...
const [grid, setGrid] = React.useState(initGrid);
...
setGrid(() => newGrid)
...
```

The result seems pretty good, I didn't notice any incoherent moves during my small manual tests, more tests are needed to validate this approach.

## Dependently update the tetris grid and piece coords

In addition of managing the grid through the useState hook, I added the coords of the currentPiece in a useState hook too.
The result seemed really good at first glance but I noticed an important issue when a piece is about to be bound to the grid (== definitely placed on the grid) and a rotation occurs.

In this case, the piece is painted in a coord where there still have a row to drop down. So definitely not a the good place.

This approach has been abandoned, but could be improved if others don't work

**Comment by jeremie-gauthier** [comment]
@nicolasvienot 
Hey !

Check out this new version !

I refacto all using the method describe in the following blog post
https://kentcdodds.com/blog/use-state-lazy-initialization-and-function-updates#dispatch-function-updates

**Review by nicolasvienot — CHANGES_REQUESTED** [review]
Hey @jeremie-gauthier 

Code looks neat! I think you found a really nice way to handle the gravity timer and the different actions together. It's nothing compared to last version, and doesn't seem to have any problem handling input events while going down automatically.

Although, I might have found a problem when you are rotating and the piece arrives to the end (end of board or another piece just behind).

I see 2 problems :
When I keep rotating and my piece fixes itself on the bottom, the next piece I will get will be the same piece. (whaaaat?)
Sometimes, when my piece tries to fix itself on another piece while I'm rotating, I get an error (see attachment). I assume the piece tries to shift but can't or is already fixed.

Would you like me to open another issue about that?
Let me know if you need more accurate steps to reproduce.

Thanks again, nice work :1st_place_medal: 

Capture d’écran du 2020-10-22 16-27-02
Capture d’écran du 2020-10-22 16-25-35

**Comment by jeremie-gauthier** [comment]
I fixed what you have noticed.
I let you merge this into `develop` if it's ok for you.
I have rebased this branch, so it should merge easily.

**Comment by nicolasvienot** [comment]
LGTM :100:

**Pull request merged**
