### PR TITLE
Gh 71

### LINKED ISSUE #71: Fix level?
Is the level in game working?
Or am I bad?
Tested in solo and multi

### PR DESCRIPTION
**Pull request by jeremie-gauthier**
I fixed this issue by creating a new custom hook `useGameStats`
This hook is responsible for the stats of the game (score, lines, level, sound speed rate)
I removed the now unused actions/reducers that was previously used to do it

### CODE REVIEW

**Comment by nicolasvienot** [comment]
@jeremie-gauthier 
On tests :
**Solo**
- When I level up, the sounds starts to accelerate (normal) but it stops after a few seconds

**Multi**
- The level doesn't display, I just have a "Level" without any number

**Comment by jeremie-gauthier** [comment]
@nicolasvienot 
I fixed the level not being displayed in **Multi**

For the other part, I was not able to reproduce this bug.

**Comment by nicolasvienot** [comment]
Can't reproduce anymore, uh. I'll merge it then. Good job!

**Review by nicolasvienot — APPROVED** [review]
LGTM

**Pull request merged**
